import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <QueryProvider>
          <div className="flex h-screen overflow-hidden">
            <aside className="w-64 bg-white border-r border-gray-200 hidden md:flex flex-col">
              <div className="h-16 flex items-center px-6 border-b border-gray-200">
                <h1 className="text-xl font-bold text-blue-600">MiniStock</h1>
              </div>
              <nav className="flex-1 p-4 space-y-1">
                <a href="#" className="flex items-center px-4 py-3 bg-blue-50 text-blue-700 rounded-lg font-medium">
                  Dashboard
                </a>
                <a href="#" className="flex items-center px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-lg font-medium">
                  Productos
                </a>
                <a href="#" className="flex items-center px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-lg font-medium">
                  Categorías
                </a>
                <a href="#" className="flex items-center px-4 py-3 text-gray-600 hover:bg-gray-50 rounded-lg font-medium">
                  Movimientos
                </a>
              </nav>
            </aside>
            <div className="flex-1 flex flex-col min-w-0">
              <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6">
                <h2 className="text-xl font-semibold text-gray-800">Dashboard</h2>
                <div className="flex items-center gap-4">
                  <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700 font-bold">
                    A
                  </div>
                </div>
              </header>
              <main className="flex-1 overflow-auto p-6">
                {children}
              </main>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
